/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c DbusPasskey -p dbuspasskey com.deepin.Passkey.xml
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef DBUSPASSKEY_H
#define DBUSPASSKEY_H

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface com.deepin.Passkey
 */
class DbusPasskey: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "com.deepin.Passkey"; }

public:
    DbusPasskey(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = nullptr);

    ~DbusPasskey();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<> Claim()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("Claim"), argumentList);
    }

    inline QDBusPendingReply<QString> DeviceDetect(int timeout)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(timeout);
        return asyncCallWithArgumentList(QStringLiteral("DeviceDetect"), argumentList);
    }

    inline QDBusPendingReply<QString> GetAssertion(const QString &user, const QString &credName, const QString &pin)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(user) << QVariant::fromValue(credName) << QVariant::fromValue(pin);
        return asyncCallWithArgumentList(QStringLiteral("GetAssertion"), argumentList);
    }

    inline QDBusPendingReply<QStringList> GetCreds(const QString &user)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(user);
        return asyncCallWithArgumentList(QStringLiteral("GetCreds"), argumentList);
    }

    inline QDBusPendingReply<int> GetDeviceCount()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("GetDeviceCount"), argumentList);
    }

    inline QDBusPendingReply<int, int> GetPinStatus()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("GetPinStatus"), argumentList);
    }
    inline QDBusReply<int> GetPinStatus(int &exist)
    {
        QList<QVariant> argumentList;
        QDBusMessage reply = callWithArgumentList(QDBus::Block, QStringLiteral("GetPinStatus"), argumentList);
        if (reply.type() == QDBusMessage::ReplyMessage && reply.arguments().count() == 2) {
            exist = qdbus_cast<int>(reply.arguments().at(1));
        }
        return reply;
    }

    inline QDBusPendingReply<int> GetValidCredCount(const QString &user)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(user);
        return asyncCallWithArgumentList(QStringLiteral("GetValidCredCount"), argumentList);
    }

    inline QDBusPendingReply<QString> MakeCredential(const QString &user, const QString &credName, const QString &pin)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(user) << QVariant::fromValue(credName) << QVariant::fromValue(pin);
        return asyncCallWithArgumentList(QStringLiteral("MakeCredential"), argumentList);
    }

    inline QDBusPendingReply<QString> Reset()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("Reset"), argumentList);
    }

    inline QDBusPendingReply<> SetPin(const QString &oldPin, const QString &newPin)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(oldPin) << QVariant::fromValue(newPin);
        return asyncCallWithArgumentList(QStringLiteral("SetPin"), argumentList);
    }

    inline QDBusPendingReply<> UnClaim()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("UnClaim"), argumentList);
    }

Q_SIGNALS: // SIGNALS
    void DeviceDetectStatus(const QString &id, int finish, int result);
    void GetAssertStatus(const QString &id, const QString &user, int finish, int result);
    void MakeCredStatus(const QString &id, const QString &user, int finish, int result);
    void ResetStatus(const QString &id, int finish, int result);
};

namespace com {
  namespace deepin {
    typedef ::DbusPasskey Passkey;
  }
}
#endif
